### ISSUE TITLE
Server crash, heartbeat_timeout and infrastructure_died

### ISSUE THREAD

**Issue by dcy** [shopgun/turtle#28] opened 2017-01-06 09:30 UTC
Hi!
My server crash suddenly, I don't know what's the problem.
```
2017-01-05 22:25:59.325 [error] <0.1045.0> gen_server <0.1045.0> terminated with reason: heartbeat_timeout
2017-01-05 22:25:59.326 [warning] <0.1032.0>@turtle_conn:handle_info:105 Lost connection to AMQP for conn_name = amqp_server
2017-01-05 22:25:59.326 [error] <0.1045.0> CRASH REPORT Process <0.1045.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:terminate/7 line 826
2017-01-05 22:25:59.329 [error] <0.1035.0> Supervisor {<0.1035.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1044.0>, {amqp_params_network,<<"hisir">>,<<"hisir123">>,<<"/">>,"10.0.0.110",5672,0,0,15,infinity,none,[...],...}) at <0.1045.0> exit with reason heartbeat_timeout in context child_terminated
2017-01-05 22:25:59.329 [error] <0.1032.0> gen_server <0.1032.0> terminated with reason: {error,{connection_down,heartbeat_timeout}}
2017-01-05 22:25:59.330 [error] <0.1032.0> CRASH REPORT Process <0.1032.0> with 0 neighbours exited with reason: {error,{connection_down,heartbeat_timeout}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.330 [error] <0.1031.0> Supervisor turtle_sup had child amqp_server started with turtle_conn:start_link(amqp_server, #{conn_name => amqp_server,connections => [{main,[{"10.0.0.110",5672}]},{backup,[{"10.0.0.110",...}]}],...}) at <0.1032.0> exit with reason {error,{connection_down,heartbeat_timeout}} in context child_terminated
2017-01-05 22:25:59.330 [debug] <0.1031.0> Supervisor turtle_sup started turtle_conn:start_link(amqp_server, #{conn_name => amqp_server,connections => [{main,[{"10.0.0.110",5672}]},{backup,[{"10.0.0.110",...}]}],...}) at pid <0.2691.0>
2017-01-05 22:25:59.330 [debug] <0.2692.0> Supervisor {<0.2692.0>,amqp_connection_sup} started amqp_connection_type_sup:start_link() at pid <0.2693.0>
2017-01-05 22:25:59.331 [debug] <0.2692.0> Supervisor {<0.2692.0>,amqp_connection_sup} started amqp_gen_connection:start_link(<0.2693.0>, {amqp_params_network,<<"hisir">>,<<"hisir123">>,<<"/">>,"10.0.0.110",5672,0,0,15,infinity,none,[...],...}) at pid <0.2694.0>
2017-01-05 22:25:59.331 [error] <0.2497.0> gen_server <0.2497.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.331 [error] <0.2501.0> gen_server <0.2501.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.331 [error] <0.2497.0> CRASH REPORT Process <0.2497.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.331 [error] <0.2501.0> CRASH REPORT Process <0.2501.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.331 [error] <0.2495.0> Supervisor {<0.2495.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.1045.0>, 9, <0.2496.0>, {<<"client 10.0.0.109:56259 -> 10.0.0.110:5672">>,9}) at <0.2497.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2017-01-05 22:25:59.332 [error] <0.2499.0> Supervisor {<0.2499.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.1045.0>, 10, <0.2500.0>, {<<"client 10.0.0.109:56259 -> 10.0.0.110:5672">>,10}) at <0.2501.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2017-01-05 22:25:59.332 [error] <0.2459.0> gen_server <0.2459.0> terminated with reason: {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2497.0>,{close,200,<<"Goodbye">>},infinity]}} in gen_server:call/3 line 212
2017-01-05 22:25:59.332 [error] <0.2459.0> CRASH REPORT Process <0.2459.0> with 0 neighbours exited with reason: {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2497.0>,{close,200,<<"Goodbye">>},infinity]}} in gen_server:terminate/7 line 814
2017-01-05 22:25:59.332 [error] <0.2467.0> gen_server <0.2467.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.332 [error] <0.2467.0> CRASH REPORT Process <0.2467.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.333 [error] <0.2473.0> gen_server <0.2473.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.333 [error] <0.2473.0> CRASH REPORT Process <0.2473.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.333 [error] <0.2481.0> gen_server <0.2481.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.333 [error] <0.2481.0> CRASH REPORT Process <0.2481.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
2017-01-05 22:25:59.333 [error] <0.2461.0> gen_server <0.2461.0> terminated with reason: {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2501.0>,{close,200,<<"Goodbye">>},infinity]}} in gen_server:call/3 line 212
2017-01-05 22:25:59.333 [error] <0.2479.0> Supervisor {<0.2479.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.1045.0>, 5, <0.2480.0>, {<<"client 10.0.0.109:56259 -> 10.0.0.110:5672">>,5}) at <0.2481.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2017-01-05 22:25:59.334 [error] <0.2461.0> CRASH REPORT Process <0.2461.0> with 0 neighbours exited with reason: {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2501.0>,{close,200,<<"Goodbye">>},infinity]}} in gen_server:terminate/7 line 814
2017-01-05 22:25:59.334 [error] <0.1031.0> Supervisor turtle_sup had child flyme_c started with turtle_publisher:start_link(flyme_c, amqp_server, [], #{confirms => true}) at <0.2459.0> exit with reason {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2497.0>,{close,200,<<"Goodbye">>},infinity]}} in context child_terminated
2017-01-05 22:25:59.415 [error] <0.2477.0> gen_server <0.2477.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59.416 [error] <0.2477.0> CRASH REPORT Process <0.2477.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826                                                                                                                                                                                
```

**Comment by dcy** [comment] 2017-01-06 09:40
the crash.log:
```
2017-01-05 22:25:59 =ERROR REPORT====
** Generic server <0.2455.0> terminating
** Last message in was {'DOWN',#Ref<0.0.3.5099>,process,<0.1032.0>,{error,{connection_down,heartbeat_timeout}}}
** When Server state == {state,amqp_server,fcm_c,<0.2489.0>,#Ref<0.0.3.5100>,#Ref<0.0.3.5099>,true,undefined,0,undefined,{track_db,#{},#{}},{0,nil}}
** Reason for termination ==
** {{{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2489.0>,{close,200,<<"Goodbye">>},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{turtle_publisher,terminate,2,[{file,"/root/hisir/hisir_msgs/_build/default/lib/turtle/src/turtle_publisher.erl"},{line,286}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,643}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,809}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-01-05 22:25:59 =ERROR REPORT====
** Generic server <0.2447.0> terminating
** Last message in was {'DOWN',#Ref<0.0.3.5065>,process,<0.1032.0>,{error,{connection_down,heartbeat_timeout}}}
** When Server state == {state,amqp_server,xiaomi_t,<0.2477.0>,#Ref<0.0.3.5066>,#Ref<0.0.3.5065>,true,undefined,0,undefined,{track_db,#{},#{}},{0,nil}}
** Reason for termination ==
** {{{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2477.0>,{close,200,<<"Goodbye">>},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{turtle_publisher,terminate,2,[{file,"/root/hisir/hisir_msgs/_build/default/lib/turtle/src/turtle_publisher.erl"},{line,286}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,643}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,809}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-01-05 22:25:59 =CRASH REPORT====
  crasher:
    initial call: turtle_publisher:init/1
    pid: <0.2455.0>
    registered_name: []
    exception exit: {{{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2489.0>,{close,200,<<"Goodbye">>},infinity]}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [turtle_sup,<0.1030.0>]
    messages: [{'DOWN',#Ref<0.0.3.5100>,process,<0.2489.0>,{infrastructure_died,{writer,send_failed,badarg}}}]
    links: [<0.1031.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 420
  neighbours:
2017-01-05 22:25:59 =ERROR REPORT====
** Generic server <0.2493.0> terminating
** Last message in was {channel_exit,8,{writer,send_failed,badarg}}
** When Server state == {state,8,<0.1045.0>,<0.2492.0>,network,{[{{<0.2457.0>,#Ref<0.0.2.96>},none,{'channel.close',200,<<"Goodbye">>,0,0},none,noflow}],[]},{just_channel,{app_initiated_close,200,<<"Goodbye">>}},<0.2494.0>,none,{<0.2457.0>,#Ref<0.0.2.79>},1,true,none,{0,nil},{0,nil},true,false}
** Reason for termination ==
** {infrastructure_died,{writer,send_failed,badarg}}
2017-01-05 22:25:59 =CRASH REPORT====
  crasher:
    initial call: turtle_publisher:init/1
    pid: <0.2447.0>
    registered_name: []
    exception exit: {{{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2477.0>,{close,200,<<"Goodbye">>},infinity]}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [turtle_sup,<0.1030.0>]
    messages: [{'DOWN',#Ref<0.0.3.5066>,process,<0.2477.0>,{infrastructure_died,{writer,send_failed,badarg}}}]
    links: [<0.1031.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 424
  neighbours:
2017-01-05 22:25:59 =CRASH REPORT====
  crasher:
    initial call: amqp_channel:init/1
    pid: <0.2493.0>
    registered_name: []
    exception exit: {{infrastructure_died,{writer,send_failed,badarg}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,826}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.2491.0>,<0.1056.0>,<0.1044.0>,<0.1035.0>,amqp_sup,<0.1018.0>]
    messages: []
    links: [<0.2491.0>]
    dictionary: [{process_name,{amqp_channel,{<<"client 10.0.0.109:56259 -> 10.0.0.110:5672">>,8}}}]
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 450
  neighbours:
```
The last console.log is
```
2017-01-05 22:25:59.418 [error] <0.2447.0> CRASH REPORT Process <0.2447.0> with 0 neighbours exited with reason: {{infrastructure_died,{writer,send_failed,badarg}},{gen_server,call,[<0.2477.0>,{close,200,<<"Goodbye">>},infinity]}} in gen_server:terminate/7 line 814
2017-01-05 22:25:59.418 [error] <0.2493.0> CRASH REPORT Process <0.2493.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 826
```
Then the server is not running.

**Comment by jlouis** [comment] 2017-01-06 11:11
We've seen this internally as well the last week. I know this much about the error at the moment:

* The network disconnects. For us, this happens all the time on AWS. Normally this is not a problem and the system will restart.
* Most of what you see is spam from the RabbitMQ amqp client, not turtle.
* We've seen the case where once the disconnect happens, turtle enters a limbo-state for prefetched messages: The RabbitMQ server thinks there are unacked in-flight messages that your service is currently working on. Yet, the messages have been thrown away in turtle. These messages "clog" the subscription and no further messages are sent to the client.

Turtle currently does a lot of `trap_exit` in an attempt to guard and gracefully close down the RabbitMQ AMQP client. Perhaps a recent update to the client code is what has created this problem since we have not seen it before.

No further investigation has happened at this moment. Eventually I'll get around to doing it, but there are no time frame unless the problem happens more in our end.

An investigation should start with a reproduction of the error. Write a "slow" turtle service, pile work on it and then use a firewall to disconnect the server and client. Use this to figure out what is going on and track down where the bug happens.

**Comment by dcy** [comment] 2017-01-07 05:54
It is a problem for me because the application server crash.
It just happened once, I use turtle 1.7.2.
I will upgrade turtle to 1.8.0.

**Comment by jlouis** [comment] 2017-07-14 14:20
May be related to #33

**Comment by jlouis** [comment] 2018-08-21 09:30
This was merged aeons ago.

**Closed by jlouis** 2018-08-21 09:30 UTC
